version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-alx_caching}
      POSTGRES_USER: ${POSTGRES_USER:-alx_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-alx_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
