version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: propertyuser
      POSTGRES_PASSWORD: propertypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
